<?php


namespace App\Http\Validations\v1;


use Illuminate\Http\Request;
use LaravelSimpleBases\Http\Validations\BaseValidation;

class ProjectValidation extends BaseValidation
{

    public function validate(Request $request, $method)
    {

        $this->fieldsCreate = [

            'name' => 'required',
            'directory' => 'required',

        ];

        parent::validate($request, $method); // TODO: Change the autogenerated stub
    }

}
