<?php


namespace App\Http\Validations\v1;


use Illuminate\Http\Request;
use LaravelSimpleBases\Http\Validations\BaseValidation;

class RepositoryValidation extends BaseValidation
{

    public function validate(Request $request, $method)
    {

        $this->fieldsCreate = [

            'project_uuid' => 'required',
            'secret' => 'required',
            'enabled' => 'required',
            'branch' => 'required',
            'https' => 'required',

        ];

        parent::validate($request, $method); // TODO: Change the autogenerated stub
    }

}
